### ISSUE TITLE
Check files in subfolders

### ISSUE THREAD

**Issue by netchester** [thehunmonkgroup/nagios-plugin-file-ages-in-dirs#4]
Can this script check files in a sub-folders ? I have a backup server under linux but after the backup path the system creates random folder (like 017ac7de-0c21-3bd3-a30c-8c217c3e62f3) and then dates. I did /path/to/folder/\* but I'm not sure if this is working.

**Comment by thehunmonkgroup** [comment]
Please refer to https://github.com/thehunmonkgroup/nagios-plugin-file-ages-in-dirs#support
