### ISSUE TITLE
Not working on solaris 10

### ISSUE THREAD

**Issue by VinxItak** [thehunmonkgroup/nagios-plugin-file-ages-in-dirs#8]
Hi, can you make it compatible with solaris ?
I have already worked on it, but i'm not a specialist.

For example, i had to modify :
#CURRENT_TIME=`date +%s`
CURRENT_TIME=`nawk "BEGIN{print srand}"`

#file_list=`find $full_path -mindepth 1 -maxdepth 1 $file_types $ignore | sort`
file_list=`find $full_path $file_types $ignore | sort`

#if [ "$OS_DISTRO" = "Linux" ]; then
#st_ctime=`stat -c%Y ${next_filepath}`
if [ "$OS_DISTRO" = "SunOS" ]; then
st_ctime=`perl -e'print ((stat("${next_filepath}"))[9]);'`

thanks

**Comment by thehunmonkgroup** [comment]
you're welcome to submit a PR to add this functionality, and i will consider it for inclusion -- this is not work i will do myself.

**Comment by VinxItak** [comment]
i managed it, I close this case
